require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '233594124438',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTVA1b0JrYUpONHQxNndPL1EyTnBUMkdlcnc4UUxQOEFlWkdCYVRuUFdGRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUThtdFgzb2FFNDNDZnc5cWVZbHVseVU2U2xCUUJqOGVIeW43T3oySCtnbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlQkVQL2UyRWFPS3ZkSE5Ea0lXemRsNFU0NzcvTVJ4SzE0MlhjOVAyUVhzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHYjc4elVWVWhvZmxBc0JSeU9uSnE5MllGL2phcmgrNXZKeG9Obkc1WFFVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBCdTNnQjg1dVlYd1UvcHBqcnFZY1RrclJHZE9iS0l6Ym5CZG5SYWdmM0k9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImxNeldLMzl4VmFDQlhNZFJnUDRDTVcySVRLSnBaRzRGdkNlcmM0TDJsemc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUtRcFlLYzhlSi9yZ2U0cFNYQUhxMEhUMy9VOXpveDh4d2N6dDVvekoxaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOXlwakt1dFVhbTByMFlKODlFdmZKK296WnVTUjRPUzMrQlVUU2pVRkxSMD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZtdHgvUnUvUzl0MENzMHZoMlJOQkIzbUQwbFdRS1d5Wk5PeHk3TUZQcUV1NWlVTW00OU1ZcThDVEZvYktDdUhDYUlROFRab3MyRXBNaG5xUENVQkN3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTEsImFkdlNlY3JldEtleSI6InFFaWlPc3l6OVY0V3lDQ1ZlNk5ZRzdRZllxeDN4bTJlYk5JQU90M2xUUU09IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjMzNTk0MTI0NDM4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkI5QjEyMUNGQTQxODkwODFBRjY4NzQwMEQ1QUUwRDcwIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTMzNzU1NTN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzMzU5NDEyNDQzOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIyMTlBNTI0QzRCODFFMzI5MDA1RTQzODNFQzFDQkE2QiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUzMzc1NTU3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzM1OTQxMjQ0MzhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQkIxQjcxQjQ1OTJCODU1Q0QxNjYzOTE4M0ZGRUQ1REUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MzM3NTU2M31dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiOEhYUTJHN0UiLCJtZSI6eyJpZCI6IjIzMzU5NDEyNDQzODoxMUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjE4Nzk5OTk2Mjg0OTUyNToxMUBsaWQiLCJuYW1lIjoi8J+MtPCdkJHwnZCI8J2QgvCdkIfinIjvuI9fKl/wn46L8J2Qi/CdkIDwnZCM8J2QgPCdkJHwn4y0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPakVvbzhIRUszR2ljUUdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJnOHBGZW1ablJPSlhIYVFhaTRITlN6NStvTHR2U2k3aVhHZXUvbWp1eGlvPSIsImFjY291bnRTaWduYXR1cmUiOiJ3UXNoQ0ZFNTlKelJLbWpKc25vSDhzRXJjbDU5dGRPblFaL1ZzdUtROTRBV3VLaXRMbmJpYm9IL1NuRFBia2JnNlo0WXNCK21USGo2UjdSTXRmeGlBQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWHJzdVgyU0tVRzhiR0VHUmxzaGRxcDlSYXIrSEhETHhFOFUrR2pRdkl4V2g4QXFTMVN4SnBKM2xUWlBNV1habjRmVEZmT3B5L1BPL1R0L29LTGg5QlE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzM1OTQxMjQ0Mzg6MTFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWVBLUlhwbVowVGlWeDJrR291QnpVcytmcUM3YjBvdTRseG5ydjVvN3NZcSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSURRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUzMzc1NTQ3LCJsYXN0UHJvcEhhc2giOiJubTNCYiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSXJNIn0=',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
